spring:
  datasource:
    url: jdbc:mysql://localhost:3306/softtechAdress
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        globally_quoted_identifiers: true

